FROM python:3.12.1

ARG OPENAI_API_KEY
ARG AZURE_STORAGE_CONNECTION_STRING
ARG AZURE_STORAGE_CONTAINER_NAME
ARG AZURE_STORAGE_CONTAINER_NAME_CONTRACTS
ARG AZURE_STORAGE_ACCOUNT
ARG GOOGLE_API_KEY
ARG GOOGLE_CSE_ID
ARG TAVILY_API_KEY
ARG OPENAI_MODEL

ENV OPENAI_API_KEY=$OPENAI_API_KEY \
    AZURE_STORAGE_CONNECTION_STRING=$AZURE_STORAGE_CONNECTION_STRING \
    AZURE_STORAGE_CONTAINER_NAME=$AZURE_STORAGE_CONTAINER_NAME \
    AZURE_STORAGE_CONTAINER_NAME_CONTRACTS=$AZURE_STORAGE_CONTAINER_NAME_CONTRACTS \
    AZURE_STORAGE_ACCOUNT=$AZURE_STORAGE_ACCOUNT \
    GOOGLE_API_KEY=$GOOGLE_API_KEY \
    GOOGLE_CSE_ID=$GOOGLE_CSE_ID \
    TAVILY_API_KEY=$TAVILY_API_KEY \
    OPENAI_MODEL=$OPENAI_MODEL
    
LABEL Maintainer="Sajana.Palanagama"

WORKDIR /usr/app/src
COPY ./app ./
RUN pip install -r requirements.txt

EXPOSE 5000

CMD [ "python", "./api.py"]